### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by rayblair06**

### CODE REVIEW

**Comment by AlexGusew** [comment]
All looks great!
Are you going to create separate commands and configurations for dev and prod builds?
image

**Comment by rayblair06** [comment]
@faustAbc whoops, missed that. I have now added `start` and `build` for `development` and `production` (Default).

**Comment by AlexGusew** [comment]
@rayblair06 nice 👍 
Some additional points to consider:
`--mode` in webpack CLI just sets `NODE_ENV` for some webpack plugins, and if they support automatic optimizations based on `NODE_ENV`, they optimize build [Docs 🔗 ](https://webpack.js.org/configuration/mode/). That's why usually we create 3 webpack config files: common one, and per one for both development and production. And in production configuration, we can add additional optimizations like CSS minification, etc [Docs 🔗 ](https://webpack.js.org/guides/production/#setup).

**Comment by AlexGusew** [comment]
Just for future acknowledgment, please don't change anything unless you want ;)

**Pull request merged**
